version: '3.9'

services:
  web:
    container_name: read-and-do
    build:
      context: .
    ports:
      - "80:5000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:5000"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./.env
  staticfiles:
    container_name: rad-staticfiles
    build:
      context: .
    volumes:
      - ./static:/static
    ports:
      - "8000:80"
