# Generated by Django 3.0 on 2021-05-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('mail_address', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('twitter_address', models.CharField(blank=True, help_text='Please Share Your Twitter Profile Address', max_length=150, null=True, verbose_name='Twitter Profile')),
                ('linkedin_address', models.CharField(blank=True, help_text='Please Share Your Linkedin Profile Address', max_length=150, null=True, verbose_name='Linkedin Profile')),
                ('github_address', models.CharField(blank=True, help_text='Please Share Your Github Profile Address', max_length=150, null=True, verbose_name='Github Profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Developer User Information',
                'db_table': 'developer_user',
                'ordering': ('-created_at',),
            },
        ),
    ]
