# Generated by Django 3.0 on 2021-04-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developeruser',
            name='github_address',
            field=models.CharField(blank=True, help_text='Please Share Your Github Profile Address', max_length=150, null=True, verbose_name='Github Profile'),
        ),
        migrations.AddField(
            model_name='developeruser',
            name='twitter_address',
            field=models.CharField(blank=True, help_text='Please Share Your Twitter Profile Address', max_length=150, null=True, verbose_name='Twitter Profile'),
        ),
    ]
