# Generated by Django 3.0 on 2021-05-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_auto_20210511_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developerusers',
            name='password',
        ),
    ]
